from __future__ import annotations

from pydantic import BaseModel, Field


class ConnexPassengerGroupUplink(BaseModel):
    """
    Raw operational Connex group as it could come from ACARS/dispatch/airline backend.

    This represents one connection / passenger group from a Connex uplink.

    Real-world ACARS-style Connex info usually contains operational connection data:

        FLT NBR | DES | GATE | ETD | LTOP

    Example:

        LH704 | MLE | Z50 | 1740 | 1659

    The pilot does NOT manually enter these values.

    Important:
    - ltop_utc = latest time on position / latest arrival position time
      so passengers can still make the connection.
    - max_extra_fuel_kg_per_pax = airline/backend value signal.
      This may not be shown in classic ACARS screenshots, but can be added by
      the airline/VA engine to indicate how much extra fuel is acceptable
      for protecting this connection.
    """

    # Internal identifier generated by the airline/backend/VA engine.
    group_id: str

    # ACARS / Connex display fields
    outbound_flight: str
    destination: str
    gate: str | None = None
    etd_utc: str
    ltop_utc: str

    # Airline/backend enrichment, not manually entered by the pilot.
    affected_pax: int = 0
    max_extra_fuel_kg_per_pax: float = 0.0

    # Optional commercial / operational enrichment.
    cabin_class: str | None = None
    value_tier: str | None = None

    # Used for automatic hotel/last-connection risk logic.
    next_viable_connection_utc: str | None = None
    last_connection_of_day: bool = False


class ConnexUplink(BaseModel):
    """
    Full Connex uplink for an inbound hub flight.

    This is modeled after an ACARS / TELEX style Connex message.

    Example display:

        AOC MSG DISPLAY
        FRA STAT TELEX

        CONNEX INFO
        ETA:1629
        ARR GATE A13
        ARR POS  A13

        FLTNBR  DES  GATE  ETD  LTOP
        LH704   MLE  Z50   1740 1659

    The pilot action is simply:
        "Apply latest Connex uplink"

    The engine then resolves:
    - affected passenger totals
    - most restrictive LTOP
    - required recovery
    - extra fuel budget
    - hotel risk
    - last connection risk
    """

    # Hub / station where the aircraft is inbound.
    # Example from ACARS: "FRA STAT TELEX"
    station: str

    # Airport code used internally by the app.
    # Example: EDDF / EDDM.
    hub_airport: str

    # Message metadata
    generated_at_utc: str | None = None
    source: str = "ACARS_CONNEX"

    # ACARS header / arrival fields
    eta_utc: str | None = None
    arrival_gate: str | None = None
    arrival_position: str | None = None

    # Connection rows
    groups: list[ConnexPassengerGroupUplink] = Field(default_factory=list)

    notes: list[str] = Field(default_factory=list)


class ConnexConnectionStatus(BaseModel):
    """
    Per-connection status after resolving the Connex uplink.

    This is UI-friendly and lets the EFB show something like:

        LH704 MLE Z50 ETD 17:40 LTOP 16:59
        Status: Protected +30 min

    or:

        Status: At risk, needs 7 min recovery
    """

    group_id: str
    outbound_flight: str
    destination: str
    gate: str | None

    etd_utc: str
    ltop_utc: str

    affected_pax: int
    max_extra_fuel_kg_per_pax: float
    fuel_budget_kg: float

    margin_to_ltop_min: float
    required_recovery_min: float

    protected: bool
    at_risk: bool
    not_recoverable: bool = False

    hotel_risk: bool = False
    last_connection_of_day: bool = False
    longhaul_connection: bool = False
    passenger_compensation_risk: bool = False


class ResolvedConnexOperationalData(BaseModel):
    """
    Output of the Connex resolver.

    This is no longer raw pilot input.
    It is operational data derived from the airline Connex uplink.

    It is meant for:
    - scenario enrichment
    - EFB explanation/debug
    - recommendation cards
    """

    station: str
    hub_airport: str

    eta_utc: str | None
    arrival_gate: str | None
    arrival_position: str | None

    affected_pax_total: int
    total_fuel_budget_kg: float
    weighted_avg_extra_fuel_kg_per_pax: float | None

    required_time_recovery_min: float
    most_restrictive_ltop_utc: str | None

    # Positive means ETA is before LTOP.
    # Negative means ETA is after LTOP and recovery is needed.
    margin_to_most_restrictive_ltop_min: float | None

    connex_protected: bool
    connex_at_risk: bool

    hotel_risk: bool
    last_connection_of_day: bool
    longhaul_connection: bool
    group_booking: bool
    passenger_compensation_risk: bool

    connections: list[ConnexConnectionStatus] = Field(default_factory=list)
    explanation: list[str] = Field(default_factory=list)